services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: server_dev
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - ./server/logs:/app/logs
    env_file:
      - ./.env

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
      args:
        VITE_BACKEND_SERVER_URL: ${VITE_BACKEND_SERVER_URL}
        VITE_CONTACT_EMAIL: ${VITE_CONTACT_EMAIL}
    container_name: client_dev
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    container_name: nginx_dev
    ports:
      - "80:80"
    volumes:
      - ./nginx/portfolio.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - client
      - server