services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.staging
    container_name: server_staging
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.staging
      args:
        VITE_BACKEND_SERVER_URL: ${VITE_BACKEND_SERVER_URL}
        VITE_CONTACT_EMAIL: ${VITE_CONTACT_EMAIL}
    container_name: client_staging
    ports:
      - "5173:5173"
    env_file:
      - ./.env
    depends_on:
      - server

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.staging
    container_name: nginx_staging
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - client
      - server